accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns=[
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

board/urls.py
from django.contrib import admin
from django.urls import path, include
from gallery import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.index)
]

gallery/urls.py
from django.urls import path
from . import views

app_name = "gallery"

urlpatterns=[
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:id>/update/', views.update, name="update"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('<int:id>/', views.detail, name="detail"),
    path('<int:id>/like', views.like, name="like"),

    path('<int:question_id>/comment_like/<int:comment_id>', views.comment_like, name="comment_like"),

    path('<int:id>/create/comment', views.create_comment, name="create_comment"),
    path('<int:question_id>/delete/comment/<int:comment_id>', views.delete_comment, name="delete_comment"),
    path('<int:question_id>/update/comment/<int:comment_id>', views.update_comment, name="update_comment"), 

]

accounts/models.py
from django.db import models

# Create your models here.

gallery/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Question(models.Model):
    kind = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes_questions')
    

class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateField(auto_now_add=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pick = models.IntegerField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes_comments')

    

gallery/forms.py
from django import forms
from .models import Question, Comment


class QuestionForm(forms.ModelForm):
    li = [
        ('식물', '식물'),
        ('동물', '동물'),
        ('영화', '영화'),
        ('음악', '음악'),
        ('드라마', '드라마'),
    ]
    kind = forms.CharField(widget =forms.Select(choices=li))
    
    class Meta:
        model = Question
        fields = ('kind', 'title', 'content',)


class CommentForm(forms.ModelForm):
    choices = [(1, '추천'), (2, '비추천')]
    pick = forms.ChoiceField(choices=choices , widget=forms.RadioSelect)
    class Meta:
        model = Comment
        fields = ('pick', 'content',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("gallery:index")
    else:
        form = UserCreationForm()
    context = {
        'form': form,
        'name': 1,
    }
    return render(request, 'accounts/form.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('gallery:index')
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('gallery:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
        'name': 2,
    }
    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('gallery:index')

gallery/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import QuestionForm, CommentForm
from .models import Question, Comment
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    questions = Question.objects.all()
    context = {
        'questions': questions,
    }
    return render(request, 'gallery/index.html', context)

@login_required
def create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            return redirect('gallery:index')
    else:
        form = QuestionForm()
    return render(request, 'gallery/form.html', {'form': form})

@login_required
def update(request, id):
    question = get_object_or_404(Question, id=id)
    if request.method == "POST":
        if question.user == request.user:
            form = QuestionForm(request.POST, instance=question)
            if form.is_valid():
                form = form.save()
                return redirect('gallery:detail', id)
    else:
        form = QuestionForm(instance=question)
    return render(request, 'gallery/form.html', {'form': form})

@login_required
def delete(request, id):
    question = get_object_or_404(Question, id=id)
    if request.method == "POST":
        if question.user == request.user:
            question.delete()
        return redirect('gallery:index')

def detail(request, id):
    question = get_object_or_404(Question, id=id)
    form = CommentForm()
    comments = Comment.objects.filter(question=question).order_by('-id')
    cnt_a = question.comment_set.filter(pick="1").count()
    cnt_b = question.comment_set.filter(pick="2").count()
    like_cnt = question.like_users.all().count()
    
    if question.comment_set.all():
        cnt_all = cnt_a + cnt_b
        ratio_a = cnt_a / cnt_all * 100
        ratio_b = cnt_b / cnt_all * 100

        cnt = {
            'ratio_a': ratio_a,
            'ratio_b': ratio_b,
            'cnt_a': cnt_a,
            'cnt_b': cnt_b,
        }
    else:
        cnt = {
            'ratio_a': '0.0',
            'ratio_b': '0.0',
            'cnt_a': cnt_a,
            'cnt_b': cnt_b,
        }

    context = {
        'question': question,
        'form': form,
        'cnt': cnt,
        'comments': comments,
        'like_cnt': like_cnt,
    }
    return render(request, 'gallery/detail.html', context)


@login_required
def like(request, id):
    question = get_object_or_404(Question, id=id)
    user = request.user

    if question.like_users.filter(id=user.id):
        question.like_users.remove(user)
    else:
        question.like_users.add(user)


    return redirect('gallery:detail', id)

@login_required
def comment_like(request, question_id, comment_id):
    # question = get_object_or_404(Question,id=question_id)
    comment = get_object_or_404(Comment,id=comment_id)
    user = request.user

    if comment.like_users.filter(id=user.id):
        comment.like_users.remove(user)
    else:
        comment.like_users.add(user)


    return redirect('gallery:detail', question_id)


@login_required
def create_comment(request, id):
    question = get_object_or_404(Question, id=id)
    if request.method == "POST":
        comment = CommentForm(request.POST)
        if comment.is_valid():
            comment = comment.save(commit=False)
            comment.question = question
            comment.user = request.user
            comment.save()
        return redirect('gallery:detail', id)

@login_required
def delete_comment(request, question_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == "POST":
        if comment.user == request.user:
            comment.delete()
        return redirect('gallery:detail', question_id)

@login_required
def update_comment(request, question_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('gallery:detail', question_id)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'gallery/form.html', {'form': form})

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% if name == 2 %}
      <input type="submit" value="log in" class="btn btn-primary">
    {% else %}
      <input type="submit" value="sign up" class="btn btn-primary">
    {% endif %}
  </form>
{% endblock %}

board/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>게시판</title>
  {% bootstrap_css%}
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap" rel="stylesheet">
  <style>
    .noto{
      font-family: 'Noto Sans KR', sans-serif;
    }
  </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light noto">
    <a class="navbar-brand" href="{% url 'gallery:index' %}">게시글 목록</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% if user.is_authenticated %}
          <a class="nav-item nav-link active" href="{% url 'gallery:create' %}">게시글 작성</a>
          <a class="nav-item nav-link disabled text-dark" href="">{{user.username}}님 환영합니다.</a>
          <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
        {% else %}
          <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
          <a class="nav-item nav-link" href="{% url 'accounts:login' %}">로그인</a>
        {% endif %}
        
      </div>
    </div>
  </nav>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>

  {% bootstrap_javascript jquery="full" %}
</body>
</html>

gallery/templates/gallery/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %} 
  <h1 class="display-4 text-center my-5">{{question.title}}</h1><br><br>
  <h3 class="">{{question.content}}</h3><br><br>
  <h5 class="text-right">{{question.created_at}}</h5>
  <h5 class="text-right">작성자 : {{question.user}}</h5>
  
  {% if question.user == user %}
    <div class="d-inline">
      <div class="text-right">
        <a href="{% url 'gallery:update' question.id %}" class="btn btn-warning">수정</a>
        <form action="{% url 'gallery:delete' question.id %}" method="POST" class="d-inline">
          {% csrf_token %}
          <input type="submit" value="삭제" class="btn btn-danger">
        </form>
      </div>
    </div>
  {% endif %} 
  <div class="progress my-3">
    <div class="progress-bar bg-primary" role="progressbar" style="width: {{cnt.ratio_a}}%">추천 : {{cnt.cnt_a}}개</div>
    <div class="progress-bar bg-danger" role="progressbar" style="width: {{cnt.ratio_b}}%">비추천 : {{cnt.cnt_b}}개</div>
  </div>

  <div class="d-flex justify-content-center">
    {% if user in question.like_users.all %}
      <a href="{% url 'gallery:like' question.id %}" class="btn btn-primary">좋아요 : {{like_cnt}}</a>
    {% else %}
      <a href="{% url 'gallery:like' question.id %}" class="btn btn-light">좋아요 : {{like_cnt}}</a>
    {% endif %}
  </div>
  <hr>

  <div class="my-2 noto">
    <form action="{% url 'gallery:create_comment' question.id %}" method="POST" class="">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="text-right">
        <input type="submit" value="등록" class="btn btn-primary">
      </div>
    </form>
  </div>

  <hr>
    <p class="noto">
      <button class="btn btn-dark col-12" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        댓글보기
      </button>
    </p>
    <div class="collapse noto" id="collapseExample">
      <div class="card card-body">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">댓글 작성자</th>
              <th scope="col">댓글 내용</th>
              <th scope="col">댓글 게시일</th>
              <th scope="col">수정 및 삭제</th>
              <th scope="col">좋아요</th>
            </tr>
          </thead>
          <tbody>
            {% for comment in comments %}
            <tr>
              <td><p class="noto">{{comment.user}}</p></td>
              <th>{{comment.content}}</th>
              <td>{{comment.created_at}}</td>
              {% if comment.user == user %}
              <td>
                <a href="{% url 'gallery:update_comment' question.id comment.id %}" class="btn btn-outline-warning">수정</a>
                <form action="{% url 'gallery:delete_comment' question.id comment.id %}" method="POST" class="d-inline">
                  {% csrf_token %}
                  <input type="submit" value="삭제" class="btn btn-outline-danger">
                </form>
              </td>
              {% else %}
                <td>
                  <h5>권한없음</h5>
                </td>
              {% endif %}
              {% if user in comment.like_users.all %}
                <td><a href="{% url 'gallery:comment_like' question.id comment.id %}" class="btn btn-primary">좋아요 {{comment.like_users.all.count}}</a></td>
              {% else %}
                <td><a href="{% url 'gallery:comment_like' question.id comment.id %}" class="btn btn-light">좋아요 {{comment.like_users.all.count}}</a></td>
              {% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>



{% endblock %}

gallery/templates/gallery/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <form action="" method="POST" class="my-5">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="올리기" class="btn btn-outline-primary">
  </form>
{% endblock %}

gallery/templates/gallery/index.html
{% extends 'base.html' %}

{% block body %} 
  <h1 class="display-4 text-center my-5">게시판</h1>
  <table class="table">
      <thead>
        <tr>
          <th scope="col">No.</th>
          <th scope="col">DISTINCT</th>
          <th scope="col">TITLE</th>
          <th scope="col">USERNAME</th>
          <th scope="col">CREATED_AT</th>
        </tr>
      </thead>
      <tbody>
        {% for question in questions %}
          <tr class="noto">
            <th scope="row">{{question.id}}</th>
            <td>{{question.kind}}</td>
            <td>
              <a href="{% url 'gallery:detail' question.id %}" class="text-dark">{{question.title}}
                <h5 class="d-inline">
                  <span class="badge badge-info mx-2">
                    {{question.comment_set.all.count}}
                  </span> 
                </h5>
              </a>
            </td>
            <td>{{question.user}}</td>
            <td><p>{{question.created_at}}</p></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}